### Create dishes
POST http://localhost:3000/dishes
Content-Type: application/json

{
  "name": "Test Dish",
  "servings": 1
}

### Read dishes
GET http://localhost:3000/dishes

### Read dish
GET http://localhost:3000/dishes/1

### Update dish
PUT http://localhost:3000/dishes
Content-Type: application/json

{
  "id": 1,
  "name": "🌽❄",
  "servings": 3
}

### Delete dish
DELETE http://localhost:3000/dishes/111
