### Create Fruit
POST http://localhost:3000/
Content-Type: application/json

{
  "name": "Mango"
}

### Update Fruit
PUT http://localhost:3000/
Content-Type: application/json
{
  "name": "Cherry"
}

### Delete Fruit
DELETE http://localhost:3000/12